src/doctor/urls.py
from django.urls import path,re_path
from .import views



app_name = 'doctor'

urlpatterns = [
	path('', views.index, name="index"),
	path('add/', views.add, name="add"),
	path('<int:id>/edit/',  views.edit, name='edit'),
	path('<int:id>/delete/', views.delete, name='delete'),

 ]

src/hms/urls.py
from django.contrib import admin
from django.conf.urls import url, re_path, include
from django.urls import include, path
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token
from django.conf import settings

from personal.views import (
	home_screen_view, dashboard_view
)
# from hms_web import urls as sarovara_urls

from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
    patient_detail,
    privacy_policy,
	must_authenticate_view,
    ValidatePhoneSendOTP,
    ValidateOTP,
    RegisterAPI,
    ResetPasswordAPIView,
    ChangePasswordAPIView,
    PasswordResetSendOTP,
    ValidateResetPasswordOTP,
    ChangePasswordAfterOtpAPIView,
    CheckTokenAPIView,
    SendMessageToMobileAPIView, # FOR SENDING SMS
    SaveUpdateFirebaseToken,     #update,save firebasetoken for sending message to user fcm
    GetUserJarAndCreditAPIView,
    GetUserCreditAndJarByStorewise,
    GetCallLogsStoreAPIView,
    MissCallUsersAPIView,
    ## hms
    PatientUserListAPIView,
    CustomerPatientUserList,
    DoctorUserListAPIView,
    VisitAPIView,
    ##fbv
    visit_type_index,
    visit_type_add,
    visit_type_edit,
    PatientDetailAPIView,
)
from account.patient_datatable import PatientDataTable



from carts.views import (
        CartAPIView,
        CartView, 
        AddToCartView,
        CartItemSaveView,
        CartTransactionView,
        RemoveCartItemFromCart,
        )

from orders.datatable import SalesDataTable
from orders.views import (
                    # AddressSelectFormView, 
                    # UserAddressCreateView,
                    AccountsVerifyRegistrationView,
                    AccountsResetPasswordView,
                    # UserAddressCreateAPIView,
                    # UserAddressListAPIView,
                    # UserCheckoutAPI,
                    OrderList,
                    OrderListAPIView, 
                    OrderDetail,
                    OrderRetrieveAPIView,
                    # SendQuotationApiView,
                    CartOrderApiView, 
                    UserOrderView,
                    UserOrderDetailView,
                    OrderLists,
                    OrderHistoryLists,
                    CartOrderLists,
                    StoreWiseCartOrderLists,
                    UpdateOrderStatusApiView,
                    StoreWiseOrderHistoryLists,
                    UpdateStoreWiseOrderStatusApiView,
                    StoreWiseOrderLists,
                    myStoreName,
                    AddNoteToOrderAPIView,
                    CustomerCancelOrderAPIView,
                    ### hms##
                    pos,
                    pos1,
                    carts,
                    cartitems,
                    visit,
                    purchase,
                    purchaseEdit,
                    purchaseDetails,
                    purchaseDetail,
                    PurchaseOrderAPIView,
                    PurchaseItemOrderAPIView,
                    AdjustmentAPIView,
                    generate_pdf,
                    )
from orders.datatable import PurchaseDataTable, AdjustmentDataTable
from products.views import (
        # APIHomeView,
        CategoryListAPIView,
        CategoryRetrieveAPIView,
        ProductListAPIView,
        ProductRetrieveAPIView,        
        CompanyListAPIView,
        BrandListAPIView,
        GenericNameListAPIView,
        ProductUnitListAPIView,        
        CommonProductListAPIView,
        AddProductAPIView,
        AllProductRetrieveAPIView,
        ProductVariationRetrieveAPIView,
        VariationByPatientAPIView,
        hmsproducts,
        sales,
        hmsdruglists,        
        drugprice_special,
        hmsproduct_detail,
        apihmsproduct_detail,
        adjustments,
        datatable,
        hmsvariations,
        VariationBatchAPIView,
        VariationBatchPriceAPIView,
        PurchaseVariationBatchAPIView,
        VariationAPIView,
        VariationBatchPriceAPIView        
    )

from prescription.views import(
    ApiPostFile
    )

from inquiry.views import (
    InquiryApiView,
    message_list,
    view_messages
    )

from users.views import (
    UserInquiryList,
    UserInquiryForPharmacist,
    DeliveryUsersByStore
    )



#API Patterns
urlpatterns = [
    url(r'^api/CheckTokenAPIView/',CheckTokenAPIView.as_view(), name="CheckTokenAPIView"),
    url(r'^accounts/', include('rest_registration.api.urls')),
    url(r'^reports/', include('reports.urls')),
    re_path(r'^api/send_sms_api/', SendMessageToMobileAPIView.as_view(), name="send_sms"),
    # re_path(r'^api/$', APIHomeView.as_view(), name='home_api'),
    re_path(r'^api/validate_mobile/', ValidatePhoneSendOTP.as_view(), name="validate_mobile"),
    re_path(r'^api/validate_otp/', ValidateOTP.as_view(), name="validate_otp"),
    re_path(r'^api/register/', RegisterAPI.as_view(), name="register"),
    re_path(r'^api/reset_password/', ResetPasswordAPIView.as_view(), name="reset_password"),
    re_path(r'^api/reset_password_otp/', PasswordResetSendOTP.as_view(), name="reset_password_otp"),
    re_path(r'^api/validate_reset_password_otp/', ValidateResetPasswordOTP.as_view(), name="validate_reset_password_otp"),
    re_path(r'^api/change_password_afterotp/', ChangePasswordAfterOtpAPIView.as_view(), name="change_password_afterotp"),
    re_path(r'^api/change_password/', ChangePasswordAPIView.as_view(), name="change_password"),
    re_path(r'^api/file_upload/$', ApiPostFile.as_view(), name='file_upload'),
    re_path(r'^api/SaveUpdateFirebaseToken/$', SaveUpdateFirebaseToken.as_view(), name="SaveUpdateFirebaseToken"),
    re_path(r'^api/GetUserJarAndCreditAPIView/$', GetUserJarAndCreditAPIView.as_view(), name="GetUserJarAndCreditAPIView"),
    re_path(r'^api/GetUserCreditAndJarByStorewise/$', GetUserCreditAndJarByStorewise.as_view(), name="GetUserCreditAndJarByStorewise"),
    re_path(r'^api/GetCallLogsStoreAPIView/$', GetCallLogsStoreAPIView.as_view(), name="GetCallLogsStoreAPIView"),
    re_path(r'^api/MissCallUsersAPIView/$', MissCallUsersAPIView.as_view(), name="MissCallUsersAPIView"),
    

    
    # re_path(r'^api/upload/(?P<filename>[^/]+)$', FileUploadView.as_view()),
    # re_path(r'^api/upload/$', FileUploadView.as_view()),


    re_path(r'^api/cart/$', CartAPIView.as_view(), name='cart_api'),
    # re_path(r'^api/checkout/$', CheckoutAPIView.as_view(), name='checkout_api'),
    # re_path(r'^api/checkout/finalize/$', CheckoutFinalizeAPIView.as_view(), name='checkout_finalize_api'),
    re_path(r'^api/auth/token/$', obtain_jwt_token, name='auth_login_api'),
    re_path(r'^api/auth/token/refresh/$', refresh_jwt_token, name='refresh_token_api'),
    # re_path(r'^api/user/address/$', UserAddressListAPIView.as_view(), name='user_address_list_api'),
    # re_path(r'^api/user/address/create/$', UserAddressCreateAPIView.as_view(), name='user_address_create_api'),
    # re_path(r'^api/user/checkout/$', UserCheckoutAPI.as_view(), name='user_checkout_api'),
    re_path(r'^api/categories/$', CategoryListAPIView.as_view(), name='categories_api'),
    re_path(r'^api/categories/(?P<pk>\d+)/$', CategoryRetrieveAPIView.as_view(), name='category_detail_api'),
    re_path(r'^api/orders/$', OrderListAPIView.as_view(), name='orders_api'),
    re_path(r'^api/CustomerCancelOrder/$', CustomerCancelOrderAPIView.as_view(), name='orders_cancel_api'),
    re_path(r'^api/AddNoteToOrder/$', AddNoteToOrderAPIView.as_view(), name='orders_notes_api'),        


    re_path(r'^api/store_orders/$', OrderLists.as_view(), name='orders_store'), ##for_customer
    

    re_path(r'^api/orders_lists/$', CartOrderLists.as_view(), name='orders_lists'), ###uptech_

    re_path(r'^api/storewise_orders/$', StoreWiseOrderLists.as_view(), name='storewise_orders_store'),
    re_path(r'^api/storewise_orders_lists/$', StoreWiseCartOrderLists.as_view(), name='storewise_orders_lists'),
    re_path(r'^api/storewise_orders_history_lists/$', StoreWiseOrderHistoryLists.as_view(), name='storewise_orders_history_lists'),
    re_path(r'^api/store_name/$', myStoreName.as_view(), name='store_name'),

    

    re_path(r'^api/orders_status/$', UpdateOrderStatusApiView.as_view(), name='orders_status_update'), ##pharms

    re_path(r'^api/storwise_change_orders_status/$', UpdateStoreWiseOrderStatusApiView.as_view(), name='storewise_orders_status_update'),


    re_path(r'^api/orders_history/$', OrderHistoryLists.as_view(), name='orders_history'),
    
    re_path(r'^api/orders/(?P<pk>\d+)/$', OrderRetrieveAPIView.as_view(), name='order_detail_api'),
    re_path(r'^api/products/$', ProductListAPIView.as_view(), name='products_api'),
    re_path(r'^api/ProductVariationRetrive/(?P<pk>\d+)/$', ProductVariationRetrieveAPIView.as_view(), name='ProductVariationRetriveApiView'),    
    re_path(r'^api/products_add/$', AddProductAPIView.as_view(), name='products_create_api'), ##pharmas
    
    re_path(r'^api/products_common/$', CommonProductListAPIView.as_view(), name='products_common_api'),

    re_path(r'^api/products/(?P<pk>\d+)/$', ProductRetrieveAPIView.as_view(), name='products_detail_api'),
    re_path(r'^api/all_products/(?P<pk>\d+)/$', AllProductRetrieveAPIView.as_view(), name='all_products_detail_api'),##Pharmas


    re_path(r'^api/create_cart/$', AddToCartView.as_view(), name="create_cart_api"),

    re_path(r'^api/CartItemSaveView/$', CartItemSaveView.as_view(), name="CartItemSaveView"),

    re_path(r'^api/delete_cart_item/(?P<pk>\d+)/$', RemoveCartItemFromCart.as_view(), name="delete_cart_item"),

    re_path(r'^api/create_order/$', CartOrderApiView.as_view(), name="create_order_api"),
    re_path(r'^api/companies/$', CompanyListAPIView.as_view(), name="company_list_api"),
    re_path(r'^api/brands/$', BrandListAPIView.as_view(), name="brands_list_api"),

src/doctor/models.py
from django.db import models

# Create your models here.

# class Department(models.Model):
#     name = models.CharField(max_length=200, blank=True, null=True)
#     created_at =   models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now=True)

#     def __str__(self):
#         return '%s' %(self.name)    

src/doctor/forms.py
from django import forms
from django.forms import ModelForm
from account.models import Account, Doctor
from department.models import Department
from specializationtype.models import SpecializationType

class DoctorForm(ModelForm):
	fk_user = forms.ModelChoiceField(queryset=Account.objects.all(), empty_label='--Select Option --', widget=forms.Select(attrs={'class':'form-control'}), required=False)
	fk_department = forms.ModelChoiceField(queryset=Department.objects.all(), empty_label='--Select Option --', widget=forms.Select(attrs={'class':'form-control'}), required=False)
	fk_specialization_type = forms.ModelChoiceField(queryset=SpecializationType.objects.all(), empty_label='--Select Option --', widget=forms.Select(attrs={'class':'form-control'}), required=False)

	class Meta:
		model = Doctor
		fields = '__all__'

src/doctor/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib import messages

from .forms import DoctorForm
from account.models import Account, Doctor


# Create your views here.
def index(request):
	doctor_list = Doctor.objects.all()
	return render(request, 'doctor/index.html', {'doctor_list': doctor_list})


def  add(request):
	fstatusType = "Create"
	fpostType = "Doctor"

	if request.method=='POST':
		doctor_details = DoctorForm(request.POST)

		if doctor_details.is_valid():
			print('Passed')
			doctor_details.save()
			return redirect('/doctor', messages.success(request, 'Doctor added successfully.', 'alert-success'))
			# return HttpResponse('Added successfully')
		else:
			print(doctor_details.errors)
			print('Failed')
			return redirect('/doctor', messages.success(request, 'All fields are required.', 'alert-success'))
	else:
		form = DoctorForm()
		
	return render(request, 'doctor/add.html', {'form':form, 'fstatusType':fstatusType, 'fpostType':fpostType})




def edit(request, id):
	doctor_details = Doctor.objects.get(id=id)

	fstatusType = "Update"
	fpostType = "Doctor Info"
	if request.method=='POST':
		form = DoctorForm(request.POST, instance=doctor_details)

		if form.is_valid():
			print('Passed')
			if form.save():
				# return redirect('/employee/%s/edit' %(emp_id), messages.success(request, 'Education Info added successfully.', 'alert-success'))
				return redirect('/doctor', messages.success(request, 'Doctor Management updated successfully', 'alert-success'))
			else:
				return redirect('/doctor', messages.success(request, 'There was a problem connecting to the server. Please try again later.', 'alert-success'))
			form.save()
			# return redirect('/employee/%s/edit' %(emp_id), messages.success(request, 'Educations Info added successfully.', 'alert-success'))
	else:
		form = DoctorForm(instance=doctor_details)

	return render(request, 'doctor/add.html', {'form':form, 'fpostType':fpostType})


def delete(request, id):
	print(id)

src/doctor/templates/doctor/add.html
{% extends 'personal/dashboard_layout/app.html' %}

{% load static %}

{% block content %}

<!-- Page-body start -->
<div class="row">
    <div class="col-sm-12">
        <div class="card-box">
            <h4 class="header-title">
                {% if fstatusType %}
                    Add New
                {% else %}
                    Update 
                {% endif %} 
                
                {{ fpostType }}
            </h4>
            
            <form action="" method="POST" data-parsley-validate="" novalidate>
                {% csrf_token %}
                <div class="row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label>Name<span class="text-danger">*</span></label>
                            {{ form.fk_user }}
                            <!-- <ul class="parsley-errors-list filled" id="parsley-id-5">
                                <li class="parsley-required">This value is required.</li>
                            </ul> -->
                        </div>

                        <div class="form-group">
                            <label>Specialization Type</label>
                            {{ form.fk_specialization_type }}
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-success waves-effect waves-light">Submit</button>
                        </div>
                    </div>

                    <div class="col-lg-6">
                        <div class="form-group">
                            <label>Department</label>
                            {{ form.fk_department }}
                        </div>
                    </div>


                </div>
            </form>
        </div>
    </div>
</div>
<!-- Page-body ends -->



{% endblock %}

src/doctor/templates/doctor/index.html
{% extends 'personal/dashboard_layout/app.html' %}

{% load static %}

{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <div class="card-box">
                <h4 class="header-title">Doctor List </h4>
                
                <div class="form-group">
                    <a href="{% url 'doctor:add' %}">
                        <button type="submit" class="btn btn-primary waves-effect waves-light">Add New</button>
                    </a>
                </div>

                <div class="table-responsive">
                    <table class="table m-0">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Department</th>
                                <th>Specialization</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% if doctor_list %}
                                {% for item in doctor_list %}
                                    <tr>
                                        <th>{{ forloop.counter }}</th>
                                        <td>{{ item.fk_user }}</td>
                                        <td>{{ item.fk_department }}</td>
                                        <td>{{ item.fk_specialization_type }}</td>
                                        <td>
                                            <a href="{% url 'doctor:edit' item.id %}"><i class="fas fa-edit">Edit</i></a>
                                            <a href="{% url 'doctor:delete' item.id %}" onclick="return confirm('Are you sure you want to delete?')"><i class="fas fa-close"></i></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}